name: Build Raspberry PI image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Install required software for building
        run: |
          sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
          dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
          qemu-utils kpartx gpg pigz
      
      - name: Build image
        run: sudo ./build.sh
        
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: raspberry-pi-image
          path: deploy/image*
          if-no-files-found: error
        
